services:
  frontend:
    build: .
    image: nazmulhasn/ibadi_dashboard:latest
    container_name: ibadi_dashboard
    restart: unless-stopped
    environment:
      - PORT=3005
      - NEXT_PUBLIC_BASE_URL=https://api.iumi.ro/api/v1
      - NEXT_PUBLIC_SOCKET_URL=https://socket.iumi.ro
      - NEXT_PUBLIC_FIREBASE_VAPID_KEY=BPuqhT1MgiVmPIOlJEUfxtFiS666cDCNQJiOrIKU4zj_5m0yN9uyESQ-G6Iba62cSux5iTpQ8dhnEaBP8DLGs0g
    expose:
      - "3005" 

 